// Code generated by mockery v2.0.0-alpha.13. DO NOT EDIT.

package clientmock

import mock "github.com/stretchr/testify/mock"

// ClientGateway is an autogenerated mock type for the ClientGateway type
type ClientGateway struct {
	mock.Mock
}

// Destroy provides a mock function with given fields:
func (_m *ClientGateway) Destroy() {
	_m.Called()
}

// GetAPIReference provides a mock function with given fields:
func (_m *ClientGateway) GetAPIReference() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBuildInfo provides a mock function with given fields:
func (_m *ClientGateway) GetBuildInfo() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResp provides a mock function with given fields: resp
func (_m *ClientGateway) GetResp(resp int) (interface{}, error) {
	ret := _m.Called(resp)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(int) interface{}); ok {
		r0 = rf(resp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(resp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Request provides a mock function with given fields: method, paramsIn
func (_m *ClientGateway) Request(method string, paramsIn interface{}) (int, error) {
	ret := _m.Called(method, paramsIn)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, interface{}) int); ok {
		r0 = rf(method, paramsIn)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = rf(method, paramsIn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Version provides a mock function with given fields:
func (_m *ClientGateway) Version() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
